version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: laravel-nova
    versions:
    - 1.10.0
    - 1.11.0
    - 1.7.0
    - 1.8.0
    - 1.9.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    timezone: Europe/Berlin
  open-pull-requests-limit: 99
